package cli

import (
	"fmt"
	"strings"
)

func Bash() string {
	var b strings.Builder
	b.WriteString(`# bash completion for rpctl — generated by rpctl completion bash
# Usage: eval "$(rpctl completion bash)"
#    or: source contrib/completions/rpctl.bash

_rpctl() {
  local cur prev cmd
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
`)
	fmt.Fprintf(&b, "  local cmds=%q\n", strings.Join(CommandNames(), " "))
	b.WriteString(`  if [[ ${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${cmds}" -- "${cur}") )
    return 0
  fi
  cmd="${COMP_WORDS[1]}"
  case "${prev}" in
    -config|-out)
      COMPREPLY=( $(compgen -f -- "${cur}") )
      return 0
      ;;
  esac
  case "${cmd}" in
`)
	for _, c := range Commands() {
		if c.Name == "help" {
			continue
		}
		b.WriteString("    " + c.Name + ")\n")
		if len(c.Subcommands) > 0 {
			names := make([]string, 0, len(c.Subcommands))
			for _, s := range c.Subcommands {
				names = append(names, s.Name)
			}
			fmt.Fprintf(&b, "      if [[ ${COMP_CWORD} -eq 2 ]]; then\n")
			fmt.Fprintf(&b, "        COMPREPLY=( $(compgen -W %q -- \"${cur}\") )\n", strings.Join(names, " "))
			b.WriteString("        return 0\n      fi\n")
		}
		if len(c.Flags) > 0 {
			flagWords := make([]string, 0, len(c.Flags))
			for _, f := range c.Flags {
				flagWords = append(flagWords, "-"+f.Name)
			}
			fmt.Fprintf(&b, "      COMPREPLY=( $(compgen -W %q -- \"${cur}\") )\n", strings.Join(flagWords, " "))
		}
		b.WriteString("      ;;\n")
	}
	b.WriteString(`    *)
      ;;
  esac
}

complete -o default -F _rpctl rpctl
`)
	return b.String()
}

func Zsh() string {
	var b strings.Builder
	b.WriteString(`#compdef rpctl
# zsh completion for rpctl — generated by rpctl completion zsh
# Usage: eval "$(rpctl completion zsh)"
#    or: fpath+=(".../contrib/completions") && compinit

_rpctl() {
  local -a commands
  commands=(
`)
	for _, c := range Commands() {
		fmt.Fprintf(&b, "    %q\n", c.Name+":"+c.Summary)
	}
	b.WriteString(`  )
  if (( CURRENT == 2 )); then
    _describe -t commands 'rpctl command' commands
    return
  fi
  case ${words[2]} in
`)
	for _, c := range Commands() {
		if c.Name == "help" {
			continue
		}
		b.WriteString("    " + c.Name + ")\n")
		if len(c.Subcommands) > 0 {
			b.WriteString("      local -a shells\n      shells=(\n")
			for _, s := range c.Subcommands {
				fmt.Fprintf(&b, "        %q\n", s.Name+":"+s.Summary)
			}
			b.WriteString("      )\n")
			b.WriteString("      if (( CURRENT == 3 )); then\n        _describe -t shells 'shell' shells\n        return\n      fi\n")
		}
		if len(c.Flags) > 0 || (len(c.Args) > 0 && len(c.Subcommands) == 0) {
			head := "      _arguments"
			if len(c.Flags) > 0 && len(c.Args) > 0 {
				head += " -S"
			}
			var specs []string
			for _, f := range c.Flags {
				spec := "'-" + f.Name + "[" + zshEscape(f.Help) + "]"
				if f.Arg != "" {
					if f.File {
						spec += ":" + f.Arg + ":_files"
					} else {
						spec += ":" + f.Arg + ":"
					}
				}
				spec += "'"
				specs = append(specs, spec)
			}
			for _, a := range c.Args {
				specs = append(specs, "'1:"+a+":'")
			}
			b.WriteString(head)
			if len(specs) == 0 {
				b.WriteByte('\n')
			} else {
				b.WriteString(" \\\n")
				for i, spec := range specs {
					b.WriteString("        " + spec)
					if i < len(specs)-1 {
						b.WriteString(" \\\n")
					} else {
						b.WriteByte('\n')
					}
				}
			}
		}
		b.WriteString("      ;;\n")
	}
	b.WriteString(`  esac
}

_rpctl
`)
	return b.String()
}

func zshEscape(s string) string {
	s = strings.ReplaceAll(s, `'`, `'"'"'`)
	s = strings.ReplaceAll(s, "[", "\\[")
	s = strings.ReplaceAll(s, "]", "\\]")
	return s
}
