# bash completion for rpctl — generated by rpctl completion bash
# Usage: eval "$(rpctl completion bash)"
#    or: source contrib/completions/rpctl.bash

_rpctl() {
  local cur prev cmd
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  local cmds="generate generate-sfa check apply add telegram-urls why probe checker completion help"
  if [[ ${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${cmds}" -- "${cur}") )
    return 0
  fi
  cmd="${COMP_WORDS[1]}"
  case "${prev}" in
    -config|-out)
      COMPREPLY=( $(compgen -f -- "${cur}") )
      return 0
      ;;
  esac
  case "${cmd}" in
    generate)
      COMPREPLY=( $(compgen -W "-config" -- "${cur}") )
      ;;
    generate-sfa)
      COMPREPLY=( $(compgen -W "-config -out" -- "${cur}") )
      ;;
    check)
      COMPREPLY=( $(compgen -W "-config" -- "${cur}") )
      ;;
    apply)
      COMPREPLY=( $(compgen -W "-config" -- "${cur}") )
      ;;
    add)
      COMPREPLY=( $(compgen -W "-config -purpose -name" -- "${cur}") )
      ;;
    telegram-urls)
      COMPREPLY=( $(compgen -W "-config" -- "${cur}") )
      ;;
    why)
      COMPREPLY=( $(compgen -W "-config" -- "${cur}") )
      ;;
    probe)
      COMPREPLY=( $(compgen -W "-config" -- "${cur}") )
      ;;
    checker)
      COMPREPLY=( $(compgen -W "-config" -- "${cur}") )
      ;;
    completion)
      if [[ ${COMP_CWORD} -eq 2 ]]; then
        COMPREPLY=( $(compgen -W "bash zsh" -- "${cur}") )
        return 0
      fi
      ;;
    *)
      ;;
  esac
}

complete -o default -F _rpctl rpctl
